## Exercise 1 — Group Comparison

**Scenario:**
You are comparing **sales for two months** to see daily trends.

**Task:**

1. Create two NumPy arrays representing sales for **5 days**:

```python
month1 = [200, 220, 250, 240, 260]
month2 = [210, 230, 240, 260, 280]
```

2. Calculate the **daily difference** in sales between month2 and month1.
3. Calculate the **percentage change** for each day.

> Tip: Use element-wise subtraction and division. Multiply by 100 for percentage.


### Step 1 — Create the arrays

In [1]:
import numpy as np 
month1 = np.array([200, 220, 250, 240, 260]) 
month2 = np.array([210, 230, 240, 260, 280])

### Step 2 — Daily difference (month2 − month1)

In [2]:
difference = month2 - month1 
print(difference)

[ 10  10 -10  20  20]


### Step 3 — Percentage change
Formula per day:

percentage change = (month2 − month1 / month1) × 100

In [3]:
percentage_change = (difference / month1) * 100 
print(percentage_change)

[ 5.          4.54545455 -4.          8.33333333  7.69230769]


## Exercise 2 — 2D Dataset (Table-like Data)

**Scenario:**
You have weekly sales data for **3 products over 4 weeks**. Aggregation will help you analyze trends.

**Task:**

1. Create a 2D NumPy array representing sales:

```python
sales_matrix = [
    [120, 130, 140, 150],
    [200, 210, 220, 230],
    [90, 100, 110, 120]
]
```

2. Calculate:

   * Total sales **per product**
   * Total sales **per week**
   * The **best-selling product** (the product with the highest total sales)

> Tip: Use `np.sum()` with the `axis` parameter and `np.argmax()`.

---

### Step 1 — Create the 2D NumPy array

In [8]:
sales_matrix = np.array([ 
    [120, 130, 140, 150], 
    [200, 210, 220, 230], 
    [90, 100, 110, 120]
      ])

### This matrix has: 
# 3 rows → products 
# 4 columns → weeks


### Step 2 — Total sales per product

In [16]:
# Sum across columns, so use axis=1:

total_per_product = np.sum(sales_matrix, axis=1) 
print(total_per_product)

[540 860 420]


### Total sales per week

In [15]:
## Sum across rows, so use axis=0:

total_per_week = np.sum(sales_matrix, axis=0) 
print(total_per_week)

[410 440 470 500]


### Best‑selling product

In [14]:
## Use np.argmax() on the product totals:

best_product_index = np.argmax(total_per_product) 
print(best_product_index)

## Since indexing starts at 0, Product 1 (the second row) is the best‑selling product.

1


## Exercise 3 — Analytical Filtering

**Scenario:**
You have a list of **product prices** and want to filter for specific price ranges.

**Task:**

1. Create a NumPy array of prices:

```python
prices = [30, 60, 90, 120, 150, 180]
```

2. Filter the prices that are:

   * Greater than 100
   * Between 50 and 150 (inclusive)

> Tip: Use boolean indexing with conditions like `prices > 100` or `(prices >= 50) & (prices <= 150)`.


### Step 1 — Create the NumPy array

In [17]:
prices = np.array([30, 60, 90, 120, 150, 180])

### Step 2 — Filter prices greater than 100

In [18]:
greater_than_100 = prices[prices > 100] 
print(greater_than_100)

[120 150 180]


### Filter prices between 50 and 150 (inclusive)

In [19]:
## Use a combined condition with &:

between_50_150 = prices[(prices >= 50) & (prices <= 150)] 
print(between_50_150)

[ 60  90 120 150]
